# -*- coding: utf-8 -*-
"""Pandas-Functions-Practice.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dT4vvis9fQl7L1sViyyx7L7qUvDwE2yR
"""

import pandas as pd
import numpy as np

df = pd.read_csv("/content/Attrition - Attrition.csv")

df.head()
df.tail()

df.isnull().sum()

df.sample()

df.info() #columns info and datatype

df.shape
df.describe() #statical view of data
df.columns

df['Age'].dtype

df=df.rename(columns = {"Age":'New_Age'})
df=df.rename(columns = {'Department':'department'})
df.head()

df.head()

#to find subcategories
df['Attrition'].value_counts()

#to convert data into numerical data
df['Attrition']=df['Attrition'].map({'Yes':0, 'No':1})

df['EducationField'].value_counts()
df['EducationField']=df['EducationField'].map({'Medical':1})
df.head()

df.columns

# -- group by with aggeration
#df.groupby('BusinessTravel')['Department'].count()

#to print row and colunm
df.shape

df[df['DailyRate']>1000]

df[df['EducationField']=='Other']

df.columns

# check datatype of each column
df.info()

#Show summary statistics for numeric columns.
df.describe(include='number')

#Show summary statistics for categorial columns.
df.describe(include='object')

df.isnull().sum()

df['New_Age']

#select multiple column
df[['New_Age','Department','MonthlyIncome']]

df.iloc[0]

df[df['New_Age']>40] #data filttering

df[df['Department']=='Sales']

#multiple column fittler
df[(df['DailyRate']>1200) & (df['New_Age']>50)]

df[(df['Department'] == 'Sales') | (df['Department'] == 'Research & Development')]

df[df['New_Age'].between(30, 40)]

df['Department'].unique()

df.isnull().sum()

#add missing value by the help of indexing
df.loc[0, 'Attrition'] = np.nan

df.head()

#df['EducationField'].replace('Other',np.nan, inplace=True)

df.head()

df.isnull().sum()

df['Attrition']=df['Attrition'].fillna(df['Attrition'].mean())
df.isnull().sum()

df.head()

#mode--> most frequent
df['EducationField']=df['EducationField'].fillna(df['EducationField'].mode()[0])

df.head()

df.dropna()

df.isnull().sum()

df['EducationField']=df['EducationField'].fillna(df['EducationField'].mean())

df.isnull().sum()

df.groupby('department').size().reset_index()
df.groupby('BusinessTravel').size()

df.head()

df.loc[0:5,['BusinessTravel','Attrition']]

df.iloc[0:5,[1,2,3,4,5]]

a=df.columns
a

df.groupby('BusinessTravel').size().reset_index(name='counts')

df.head()

df['department']=df['department'].map({'sales':1})

df.head()

df.isnull().sum()

df['department'].fillna(1, inplace=True)

df.isnull().sum().sum()

df.rename(columns=({'department':'new_department'}))

